version: '3.8'

services:
  bookoff_search_backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DATA_DIR=/app/data
      - TZ=Asia/Tokyo
    ports:
      - "8000:8000"

  bookoff_search_frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DATA_DIR=/app/data
      - TZ=Asia/Tokyo
    ports:
      - "8501:8501"